name: Deploy React Site
on:
  push:
    branches:
      - main
    paths:
      - 'react/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies and build
        working-directory: ./react
        run: |
          npm install
          npm run build
      - name: Deploy React site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: react-live
          folder: react/out
